import { StyleSheet } from "react-native";

export default StyleSheet.create({
  pageContainer: {
    flex: 1,
    height: "100%",
  },
  button: {
    borderRadius: 10,
    width: "100%",
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "black",
  },
  buttonText: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "white",
    marginRight: 12,
  },
  buttonSecondary: {
    borderRadius: 10,
    width: "100%",
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "lightgrey",
  },
  buttonSecondaryText: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "black",
    marginRight: 12,
  },
  buttonSquare: {
    borderRadius: 10,
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "black",
  },
  buttonSquareSmall: {
    borderRadius: 10,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "black",
  },
  accordionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  accordionContent: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    marginTop: 12,
  },
  headerText: {
    fontSize: 24,
    fontWeight: "bold",
  },
  textInput: {
    height: 44,
    borderColor: "gray",
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
  },
  areaInput: {
    height: 120,
    borderColor: "gray",
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
  },
});
