import { StyleSheet } from "react-native";

export default StyleSheet.create({
  pageContainer: {
    flex: 1,
    height: "100%",
  },
  rowContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rowSpacedContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  button: {
    borderRadius: 10,
    width: "100%",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "black",
    borderWidth: 2,
    borderColor: "black",
  },
  buttonText: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "white",
  },
  buttonSecondary: {
    borderRadius: 10,
    width: "100%",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    borderWidth: 2,
    borderColor: "black",
  },
  buttonSecondaryText: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "black",
    marginRight: 12,
  },
  buttonSquare: {
    borderRadius: 10,
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "black",
  },
  buttonSquareSmall: {
    borderRadius: 10,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "black",
  },
  buttonStretchSmall: {
    borderRadius: 10,
    minWidth: 36,
    height: 36,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "black",
  },
  buttonDisabled: {
    backgroundColor: "lightgray",
  },
  buttonGroupHorizontal: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  accordionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  accordionContent: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    marginTop: 12,
  },
  headerText: {
    fontSize: 24,
    fontWeight: "bold",
  },
  textInput: {
    height: 50,
    borderWidth: 0.5,
    borderRadius: 10,
    padding: 12,
    borderColor: "gray",
  },
  textInputError: {
    borderColor: "red",
    borderWidth: 2,
  },
  areaInput: {
    height: 120,
    borderColor: "gray",
    borderWidth: 0.5,
    borderRadius: 10,
    padding: 12,
  },
  textDisabled: {
    color: "lightgray",
  },
  textSecondary: {
    color: "gray",
  },
});
